name: GitHub Readme YouTube Cards

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate YouTube Cards
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCGq5yQ8jayw0Hb_ihViZdXQ
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#181825", "title_color": "#cdd6f4", "stats_color": "#a6adc8" }'
          max_title_lines: 2
          output_type: html
          max_videos: 4
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add README.md && git commit -m "Update YouTube cards" && git push)
